
# THIS FILE IS MEANT TO BE AN EXAMPLE DOCKER COMPOSE FILE TO RUN THE BOT

version: "3.8"

services:   
  # Database service for the bot
  db:
    image: postgres:14-alpine
    restart: unless-stopped
    volumes:
      # Database persistence volume
      - type: volume
        source: pgdata
        target: /var/lib/postgresql/data
      # Socket volume to communicate faster
      - type: volume
        source: dbsocket
        target: /var/run/postgresql
    ports:
      - 5432:5432
    environment:
      # CHANGE THE PASSWORD BEFORE DEPLOYMENT
      POSTGRES_PASSWORD: I8dGFYxxoWrq
      POSTGRES_DB: inhouse_bot

  # Simple database management tool (will use the password you set for the db service)
  adminer:
    image: adminer
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - 8080:8080


volumes:
  pgdata:     # Persistent data volume for the database
  dbsocket:   # Socket mounting volume

